/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ivanovs 2.6.11.4-21.7-default #1 Tue Jul 12 16:54:41 MSD 2005 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Пнд Сен 19 15:52:08 MSD 2005"
#define BUILD_ENV_SRCDIR "/home/isv/stuff/samba-3.0.20/source"
#define BUILD_ENV_BUILDDIR "/home/isv/stuff/samba-3.0.20/source"
#define BUILD_ENV_USER "isv"
#define BUILD_ENV_HOST "ivanovs"
#define BUILD_ENV_COMPILER "gcc"
#endif /* _BUILD_ENV_H */
