/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux isv-master 2.4.19-4GB #1 Fri Sep 13 13:19:15 UTC 2002 i686 unknown"
#define BUILD_ENV_DATE "Sun Sep 28 19:30:09 MSD 2003"
#define BUILD_ENV_SRCDIR "/home/isv/stuff/samba-3.0.0/source"
#define BUILD_ENV_BUILDDIR "/home/isv/stuff/samba-3.0.0/source"
#define BUILD_ENV_USER "isv"
#define BUILD_ENV_HOST "isv-master"
#define BUILD_ENV_COMPILER "gcc"
#endif /* _BUILD_ENV_H */
