/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ivanov_s.avp.ru 2.4.19-16mdkcustom #5 SMP Птн Мар 14 14:29:21 MSK 2003 i686 unknown unknown GNU/Linux"
#define BUILD_ENV_DATE "Птн Фев 20 11:48:13 MSK 2004"
#define BUILD_ENV_SRCDIR "/home/isv/stuff/samba-3.0.2a/source"
#define BUILD_ENV_BUILDDIR "/home/isv/stuff/samba-3.0.2a/source"
#define BUILD_ENV_USER "isv"
#define BUILD_ENV_HOST "ivanov_s.avp.ru"
#define BUILD_ENV_COMPILER "gcc"
#endif /* _BUILD_ENV_H */
