/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ivanovs.avp.ru 2.4.19-16mdkcustom #10 SMP Пнд Апр 26 16:32:29 MSD 2004 i686 unknown unknown GNU/Linux"
#define BUILD_ENV_DATE "Втр Фев  8 12:37:43 MSK 2005"
#define BUILD_ENV_SRCDIR "/home/isv/stuff/samba-3.0.11/source"
#define BUILD_ENV_BUILDDIR "/home/isv/stuff/samba-3.0.11/source"
#define BUILD_ENV_USER "isv"
#define BUILD_ENV_HOST "ivanovs.avp.ru"
#define BUILD_ENV_COMPILER "gcc"
#endif /* _BUILD_ENV_H */
